[data]
steps_per_day = 288
tod_embedding_dim = 32
dow_embedding_dim = 32
num_nodes = 307
dsp = 32
dsu = 32
in_steps = 24
out_steps = 12
lag = 24
horizon = 12
val_ratio = 0.2
test_ratio = 0.2

normalizer = std
column_wise = False

[model]
embed_dim = 10
rnn_units = 64
num_layers = 2
mp_num_workers = 8
accelerate = True

input_dim = 1
output_dim = 1
cheb_order = 2

[train]
batch_size = 32
epochs = 100
lr_init = 0.003
num_runs = 1

loss_func = mae
seed = 12
lr_decay = True
lr_decay_rate = 0.3
lr_decay_step = 20,40,70
early_stop = True
early_stop_patience = 15
grad_norm = False
max_grad_norm = 5
real_value = True

[test]
mae_thresh = None
mape_thresh = 0.

[log]
log_step = 20
plot = False